### ISSUE TITLE
Inconvenient Scrolling in "Selected Catkeys:"

### ISSUE THREAD

**Issue by TejasMate** [HaikuArchives/KeymapSwitcher#11]
While the scrolling down in  **Selected Keymaps:** then effect of Inconvenient Scrolling will display.

![Inconvenient Scrolling in Selected Catkeys](https://user-images.githubusercontent.com/14368643/72991335-d4962100-3e17-11ea-8468-51bdb5597b52.gif)

Here, After **Japanese (system)** and scrolling technique is changing.

**Comment by diversys** [comment]
This could be a Haiku bug. Could you check there with FileTypes preflet?

**Comment by TejasMate** [comment]
Yaa, it will be a bug in Haiku. I have no idea about FileTypes preflet

**Comment by diversys** [comment]
@waddlesplash is this by any chance fixed by
https://git.haiku-os.org/haiku/commit/?h=hrev54130?

**Comment by waddlesplash** [comment]
Possibly, someone needs to test.

**Comment by diversys** [comment]
@X547 can you tell? :)

**Comment by diversys** [comment]
Confirmed as fixed.
