### ISSUE TITLE
KeymapSwitcher is not installed in Deskbar

### ISSUE THREAD

**Issue by Lan72** [HaikuArchives/KeymapSwitcher#4]
After the last updates of the night builds, starting somewhere from hrev51659-60, KeymapSwitcher ceased to be installed in Deskbar. It's impossible to install in Deskbar and earlier versions of KeymapSwitcher.

When restart or shutdown computer, Deskbar crashes and gives an error.
Debug information is attached. Perhaps the problem is not in KeymapSwitcher, but in the last night builds? But all other programs, as before, are quite successfully installed in Deskbar.

[Deskbar-26271-debug-08-12-2017-22-15-40.report.txt](https://github.com/HaikuArchives/KeymapSwitcher/files/1544006/Deskbar-26271-debug-08-12-2017-22-15-40.report.txt)

**Comment by diversys** [comment]
Can't reproduce it here.

**Comment by diversys** [comment]
It was a problem with corrupted settings file.
